# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/xilinx14.7/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "F:/ZYNQ/ZingNano/Zingnano_test/SNOWLeo_Sdr_Demo/SNOWLeo_Sdr_Demo0509_14.7rls/pldma.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "f:/ZYNQ/ZingNano/Zingnano_test/SNOWLeo_Sdr_Demo/SNOWLeo_Sdr_Demo0509_14.7rls/pldma.srcs/sources_1/ip/chipscope_ila_v1_05_a_0/coregen.cgc"

set ipFile "f:/ZYNQ/ZingNano/Zingnano_test/SNOWLeo_Sdr_Demo/SNOWLeo_Sdr_Demo0509_14.7rls/pldma.srcs/sources_1/ip/chipscope_ila_v1_05_a_0/chipscope_ila_v1_05_a_0.xco"

set ipName "chipscope_ila_v1_05_a_0"

set vlnv "xilinx.com:ip:chipscope_ila:1.05.a"

set cgPartSpec "xc7z010-1clg400"

set bomFilePath "f:/ZYNQ/ZingNano/Zingnano_test/SNOWLeo_Sdr_Demo/SNOWLeo_Sdr_Demo0509_14.7rls/pldma.srcs/sources_1/ip/chipscope_ila_v1_05_a_0/pa_cg_bom.xml"

set hdlType "Verilog"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

# configure the IP
set result [source "c:/xilinx14.7/14.7/ISE_DS/PlanAhead/scripts/pa_cg_config_core.tcl"]

exit $result

