# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories true

set tclUtilsPath "h:/IDE14_7/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "J:/zing_pro/snowleo/SnowLeo_SDR_v14_7_ngc/pldma.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "j:/zing_pro/snowleo/SnowLeo_SDR_v14_7_ngc/pldma.srcs/sources_1/ip/clk_wiz_v3_6_1/coregen.cgc"

set ipFile "j:/zing_pro/snowleo/SnowLeo_SDR_v14_7_ngc/pldma.srcs/sources_1/ip/clk_wiz_v3_6_1/clk_wiz_v3_6_1.xco"

set ipName "clk_wiz_v3_6_1"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "j:/zing_pro/snowleo/SnowLeo_SDR_v14_7_ngc/pldma.srcs/sources_1/ip/clk_wiz_v3_6_1/pa_cg_bom.xml"

set cgPartSpec "xc7z010-1clg400"

set hdlType "Verilog"

# generate the IP
set result [source "h:/IDE14_7/14.7/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

