
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xnandps.h"

/*
* The configuration table for devices
*/

XNandPs_Config XNandPs_ConfigTable[] =
{
	{
		XPAR_PS7_NAND_0_DEVICE_ID,
		XPAR_PS7_NAND_0_SMC_BASEADDR,
		XPAR_PS7_NAND_0_BASEADDR,
		XPAR_PS7_NAND_0_NAND_WIDTH
	}
};


