######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

proc _main_ {} {
  cd "F:/ZYNQ/ZingNano/Zingnano_test/SNOWLeo_Sdr_Demo/SNOWLeo_Sdr_Demo/pldma.srcs/sources_1/edk/cpu0"
  if { [ catch {xload xmp cpu0.xmp} result ] } {
    exit 10
  }
  xset arch zynq
  xset dev xc7z010
  xset package clg400
  xset speedgrade -1

xset binfo 

  save proj
  return $result
}

# Execute set part
if { [catch {_main_} result] } {
  exit -1
}

# Check return status and exit
if { [string length $result] == 0 } {
  exit 0
} else {
  exit $result
}
