######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "J:/zing_pro/zing_pldma_v144/pldma.srcs/sources_1/edk/cpu0"
if { [xload new cpu0.xmp] != 0 } {
  exit -1
}
xset arch zynq
xset dev xc7z020
xset package clg484
xset speedgrade -1

xset binfo 

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl verilog
save proj
exit
